/****************************************************************************
** Meta object code from reading C++ file 'common.h'
**
** Created by: The Qt Meta Object Compiler version 67 (Qt 5.7.0)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include "../../common/common.h"
#include <QtCore/qbytearray.h>
#include <QtCore/qmetatype.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'common.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 67
#error "This file was generated using the moc from 5.7.0. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

QT_BEGIN_MOC_NAMESPACE
struct qt_meta_stringdata_Common_t {
    QByteArrayData data[121];
    char stringdata0[2488];
};
#define QT_MOC_LITERAL(idx, ofs, len) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_Common_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
static const qt_meta_stringdata_Common_t qt_meta_stringdata_Common = {
    {
QT_MOC_LITERAL(0, 0, 6), // "Common"
QT_MOC_LITERAL(1, 7, 10), // "APP_MODULE"
QT_MOC_LITERAL(2, 18, 15), // "APP_MODULE_MAIM"
QT_MOC_LITERAL(3, 34, 19), // "APP_MODULE_SECURITY"
QT_MOC_LITERAL(4, 54, 19), // "APP_MODULE_MYWALLET"
QT_MOC_LITERAL(5, 74, 22), // "APP_MODULE_PARK_RECORD"
QT_MOC_LITERAL(6, 97, 18), // "APP_MODULE_VEHICLE"
QT_MOC_LITERAL(7, 116, 18), // "APP_MODULE_SETTING"
QT_MOC_LITERAL(8, 135, 8), // "PAY_MODE"
QT_MOC_LITERAL(9, 144, 15), // "PAY_MODE_PREPAY"
QT_MOC_LITERAL(10, 160, 16), // "PAY_MODE_POSTPAY"
QT_MOC_LITERAL(11, 177, 10), // "PAY_SOURCE"
QT_MOC_LITERAL(12, 188, 20), // "PAY_SOURCE_USER_PARK"
QT_MOC_LITERAL(13, 209, 21), // "PAY_SOURCE_USER_WXPAY"
QT_MOC_LITERAL(14, 231, 22), // "PAY_SOURCE_USER_ALIPAY"
QT_MOC_LITERAL(15, 254, 27), // "PAY_SOURCE_USER_BAIDUWALLET"
QT_MOC_LITERAL(16, 282, 20), // "PAY_SOURCE_USER_BANK"
QT_MOC_LITERAL(17, 303, 22), // "PAY_SOURCE_USER_COUPON"
QT_MOC_LITERAL(18, 326, 29), // "PAY_SOURCE_USER_CITYSMARTCARD"
QT_MOC_LITERAL(19, 356, 20), // "PAY_SOURCE_USER_CASH"
QT_MOC_LITERAL(20, 377, 24), // "PAY_SOURCE_OWNER_PARKING"
QT_MOC_LITERAL(21, 402, 22), // "PAY_SOURCE_OWNER_WXPAY"
QT_MOC_LITERAL(22, 425, 23), // "PAY_SOURCE_OWNER_ALIPAY"
QT_MOC_LITERAL(23, 449, 28), // "PAY_SOURCE_OWNER_BAIDUWALLET"
QT_MOC_LITERAL(24, 478, 21), // "PAY_SOURCE_OWNER_BANK"
QT_MOC_LITERAL(25, 500, 23), // "PAY_SOURCE_OWNER_COUPON"
QT_MOC_LITERAL(26, 524, 30), // "PAY_SOURCE_OWNER_CITYSMARTCARD"
QT_MOC_LITERAL(27, 555, 21), // "PAY_SOURCE_OWNER_CASH"
QT_MOC_LITERAL(28, 577, 3), // "CMD"
QT_MOC_LITERAL(29, 581, 16), // "CMD_APP_REGISTER"
QT_MOC_LITERAL(30, 598, 13), // "CMD_APP_LOGIN"
QT_MOC_LITERAL(31, 612, 14), // "CMD_APP_LOGOUT"
QT_MOC_LITERAL(32, 627, 20), // "CMD_APP_RESET_PASSWD"
QT_MOC_LITERAL(33, 648, 21), // "CMD_APP_MODIFY_PASSWD"
QT_MOC_LITERAL(34, 670, 19), // "CMD_APP_SET_PAYCODE"
QT_MOC_LITERAL(35, 690, 16), // "CMD_APP_RECHARGE"
QT_MOC_LITERAL(36, 707, 27), // "CMD_APP_GET_RECHARGE_RECORD"
QT_MOC_LITERAL(37, 735, 20), // "CMD_APP_PARKING_NEAR"
QT_MOC_LITERAL(38, 756, 15), // "CMD_APP_PARKING"
QT_MOC_LITERAL(39, 772, 20), // "CMD_APP_PARK_CONFIRM"
QT_MOC_LITERAL(40, 793, 19), // "CMD_APP_PARK_PREPAY"
QT_MOC_LITERAL(41, 813, 16), // "CMD_APP_PARK_FEE"
QT_MOC_LITERAL(42, 830, 21), // "CMD_APP_PARK_RESTTIME"
QT_MOC_LITERAL(43, 852, 19), // "CMD_APP_PARK_SETTLE"
QT_MOC_LITERAL(44, 872, 22), // "CMD_APP_GET_PARK_UNPAY"
QT_MOC_LITERAL(45, 895, 24), // "CMD_APP_PARK_PAY_IN_BACK"
QT_MOC_LITERAL(46, 920, 23), // "CMD_APP_GET_PARK_RECORD"
QT_MOC_LITERAL(47, 944, 24), // "CMD_APP_CHECK_FOR_UPDATE"
QT_MOC_LITERAL(48, 969, 19), // "CMD_APP_GET_SYSINFO"
QT_MOC_LITERAL(49, 989, 16), // "CMD_APP_FEEDBACK"
QT_MOC_LITERAL(50, 1006, 22), // "CMD_APP_CALL_ATTENDANT"
QT_MOC_LITERAL(51, 1029, 18), // "CMD_APP_GET_CREDIT"
QT_MOC_LITERAL(52, 1048, 19), // "CMD_APP_ADD_VEHICLE"
QT_MOC_LITERAL(53, 1068, 19), // "CMD_APP_DEL_VEHICLE"
QT_MOC_LITERAL(54, 1088, 22), // "CMD_APP_UPDATE_VEHICLE"
QT_MOC_LITERAL(55, 1111, 14), // "CMD_APP_LOCATE"
QT_MOC_LITERAL(56, 1126, 14), // "CMD_APP_ALIPAY"
QT_MOC_LITERAL(57, 1141, 13), // "CMD_APP_WXPAY"
QT_MOC_LITERAL(58, 1155, 20), // "CMD_HANDSET_REGISTER"
QT_MOC_LITERAL(59, 1176, 17), // "CMD_HANDSET_LOGIN"
QT_MOC_LITERAL(60, 1194, 18), // "CMD_HANDSET_LOGOUT"
QT_MOC_LITERAL(61, 1213, 25), // "CMD_HANDSET_ENQUIRY_SPACE"
QT_MOC_LITERAL(62, 1239, 26), // "CMD_HANDSET_PUSH_SPACEINFO"
QT_MOC_LITERAL(63, 1266, 24), // "CMD_HANDSET_BIND_CAR_BAY"
QT_MOC_LITERAL(64, 1291, 24), // "CMD_HANDSET_PARK_CONFIRM"
QT_MOC_LITERAL(65, 1316, 20), // "CMD_HANDSET_PARK_FEE"
QT_MOC_LITERAL(66, 1337, 25), // "CMD_HANDSET_PARK_RESTTIME"
QT_MOC_LITERAL(67, 1363, 23), // "CMD_HANDSET_PARK_SETTLE"
QT_MOC_LITERAL(68, 1387, 26), // "CMD_HANDSET_GET_PARK_UNPAY"
QT_MOC_LITERAL(69, 1414, 28), // "CMD_HANDSET_PARK_PAY_IN_BACK"
QT_MOC_LITERAL(70, 1443, 22), // "CMD_HANDSET_PARK_QUERY"
QT_MOC_LITERAL(71, 1466, 24), // "CMD_HANDSET_RESP_CALLING"
QT_MOC_LITERAL(72, 1491, 23), // "CMD_SENSOR_UPDATE_SPACE"
QT_MOC_LITERAL(73, 1515, 12), // "CMD_MAXIMIZE"
QT_MOC_LITERAL(74, 1528, 6), // "ERR_NO"
QT_MOC_LITERAL(75, 1535, 6), // "ERR_OK"
QT_MOC_LITERAL(76, 1542, 11), // "ERR_NETWORK"
QT_MOC_LITERAL(77, 1554, 16), // "ERR_APP_REGISTER"
QT_MOC_LITERAL(78, 1571, 13), // "ERR_APP_LOGIN"
QT_MOC_LITERAL(79, 1585, 14), // "ERR_APP_LOGOUT"
QT_MOC_LITERAL(80, 1600, 20), // "ERR_APP_RESET_PASSWD"
QT_MOC_LITERAL(81, 1621, 21), // "ERR_APP_MODIFY_PASSWD"
QT_MOC_LITERAL(82, 1643, 19), // "ERR_APP_SET_PAYCODE"
QT_MOC_LITERAL(83, 1663, 16), // "ERR_APP_RECHARGE"
QT_MOC_LITERAL(84, 1680, 27), // "ERR_APP_GET_RECHARGE_RECORD"
QT_MOC_LITERAL(85, 1708, 20), // "ERR_APP_PARKING_NEAR"
QT_MOC_LITERAL(86, 1729, 15), // "ERR_APP_PARKING"
QT_MOC_LITERAL(87, 1745, 20), // "ERR_APP_PARK_CONFIRM"
QT_MOC_LITERAL(88, 1766, 19), // "ERR_APP_PARK_PREPAY"
QT_MOC_LITERAL(89, 1786, 16), // "ERR_APP_PARK_FEE"
QT_MOC_LITERAL(90, 1803, 21), // "ERR_APP_PARK_RESTTIME"
QT_MOC_LITERAL(91, 1825, 19), // "ERR_APP_PARK_SETTLE"
QT_MOC_LITERAL(92, 1845, 22), // "ERR_APP_GET_PARK_UNPAY"
QT_MOC_LITERAL(93, 1868, 24), // "ERR_APP_PARK_PAY_IN_BACK"
QT_MOC_LITERAL(94, 1893, 23), // "ERR_APP_GET_PARK_RECORD"
QT_MOC_LITERAL(95, 1917, 24), // "ERR_APP_CHECK_FOR_UPDATE"
QT_MOC_LITERAL(96, 1942, 19), // "ERR_APP_GET_SYSINFO"
QT_MOC_LITERAL(97, 1962, 16), // "ERR_APP_FEEDBACK"
QT_MOC_LITERAL(98, 1979, 22), // "ERR_APP_CALL_ATTENDANT"
QT_MOC_LITERAL(99, 2002, 18), // "ERR_APP_GET_CREDIT"
QT_MOC_LITERAL(100, 2021, 19), // "ERR_APP_ADD_VEHICLE"
QT_MOC_LITERAL(101, 2041, 19), // "ERR_APP_DEL_VEHICLE"
QT_MOC_LITERAL(102, 2061, 22), // "ERR_APP_UPDATE_VEHICLE"
QT_MOC_LITERAL(103, 2084, 14), // "ERR_APP_ALIPAY"
QT_MOC_LITERAL(104, 2099, 13), // "ERR_APP_WXPAY"
QT_MOC_LITERAL(105, 2113, 20), // "ERR_HANDSET_REGISTER"
QT_MOC_LITERAL(106, 2134, 17), // "ERR_HANDSET_LOGIN"
QT_MOC_LITERAL(107, 2152, 18), // "ERR_HANDSET_LOGOUT"
QT_MOC_LITERAL(108, 2171, 25), // "ERR_HANDSET_ENQUIRY_SPACE"
QT_MOC_LITERAL(109, 2197, 26), // "ERR_HANDSET_PUSH_SPACEINFO"
QT_MOC_LITERAL(110, 2224, 26), // "ERR_HANDSET_BIND_CAR_SPACE"
QT_MOC_LITERAL(111, 2251, 24), // "ERR_HANDSET_PARK_CONFIRM"
QT_MOC_LITERAL(112, 2276, 20), // "ERR_HANDSET_PARK_FEE"
QT_MOC_LITERAL(113, 2297, 25), // "ERR_HANDSET_PARK_RESTTIME"
QT_MOC_LITERAL(114, 2323, 23), // "ERR_HANDSET_PARK_SETTLE"
QT_MOC_LITERAL(115, 2347, 26), // "ERR_HANDSET_GET_PARK_UNPAY"
QT_MOC_LITERAL(116, 2374, 28), // "ERR_HANDSET_PARK_PAY_IN_BACK"
QT_MOC_LITERAL(117, 2403, 22), // "ERR_HANDSET_PARK_QUERY"
QT_MOC_LITERAL(118, 2426, 23), // "ERR_SENSOR_UPDATE_SPACE"
QT_MOC_LITERAL(119, 2450, 24), // "ERR_HANDSET_RESP_CALLING"
QT_MOC_LITERAL(120, 2475, 12) // "ERR_MAXIMIZE"

    },
    "Common\0APP_MODULE\0APP_MODULE_MAIM\0"
    "APP_MODULE_SECURITY\0APP_MODULE_MYWALLET\0"
    "APP_MODULE_PARK_RECORD\0APP_MODULE_VEHICLE\0"
    "APP_MODULE_SETTING\0PAY_MODE\0PAY_MODE_PREPAY\0"
    "PAY_MODE_POSTPAY\0PAY_SOURCE\0"
    "PAY_SOURCE_USER_PARK\0PAY_SOURCE_USER_WXPAY\0"
    "PAY_SOURCE_USER_ALIPAY\0"
    "PAY_SOURCE_USER_BAIDUWALLET\0"
    "PAY_SOURCE_USER_BANK\0PAY_SOURCE_USER_COUPON\0"
    "PAY_SOURCE_USER_CITYSMARTCARD\0"
    "PAY_SOURCE_USER_CASH\0PAY_SOURCE_OWNER_PARKING\0"
    "PAY_SOURCE_OWNER_WXPAY\0PAY_SOURCE_OWNER_ALIPAY\0"
    "PAY_SOURCE_OWNER_BAIDUWALLET\0"
    "PAY_SOURCE_OWNER_BANK\0PAY_SOURCE_OWNER_COUPON\0"
    "PAY_SOURCE_OWNER_CITYSMARTCARD\0"
    "PAY_SOURCE_OWNER_CASH\0CMD\0CMD_APP_REGISTER\0"
    "CMD_APP_LOGIN\0CMD_APP_LOGOUT\0"
    "CMD_APP_RESET_PASSWD\0CMD_APP_MODIFY_PASSWD\0"
    "CMD_APP_SET_PAYCODE\0CMD_APP_RECHARGE\0"
    "CMD_APP_GET_RECHARGE_RECORD\0"
    "CMD_APP_PARKING_NEAR\0CMD_APP_PARKING\0"
    "CMD_APP_PARK_CONFIRM\0CMD_APP_PARK_PREPAY\0"
    "CMD_APP_PARK_FEE\0CMD_APP_PARK_RESTTIME\0"
    "CMD_APP_PARK_SETTLE\0CMD_APP_GET_PARK_UNPAY\0"
    "CMD_APP_PARK_PAY_IN_BACK\0"
    "CMD_APP_GET_PARK_RECORD\0"
    "CMD_APP_CHECK_FOR_UPDATE\0CMD_APP_GET_SYSINFO\0"
    "CMD_APP_FEEDBACK\0CMD_APP_CALL_ATTENDANT\0"
    "CMD_APP_GET_CREDIT\0CMD_APP_ADD_VEHICLE\0"
    "CMD_APP_DEL_VEHICLE\0CMD_APP_UPDATE_VEHICLE\0"
    "CMD_APP_LOCATE\0CMD_APP_ALIPAY\0"
    "CMD_APP_WXPAY\0CMD_HANDSET_REGISTER\0"
    "CMD_HANDSET_LOGIN\0CMD_HANDSET_LOGOUT\0"
    "CMD_HANDSET_ENQUIRY_SPACE\0"
    "CMD_HANDSET_PUSH_SPACEINFO\0"
    "CMD_HANDSET_BIND_CAR_BAY\0"
    "CMD_HANDSET_PARK_CONFIRM\0CMD_HANDSET_PARK_FEE\0"
    "CMD_HANDSET_PARK_RESTTIME\0"
    "CMD_HANDSET_PARK_SETTLE\0"
    "CMD_HANDSET_GET_PARK_UNPAY\0"
    "CMD_HANDSET_PARK_PAY_IN_BACK\0"
    "CMD_HANDSET_PARK_QUERY\0CMD_HANDSET_RESP_CALLING\0"
    "CMD_SENSOR_UPDATE_SPACE\0CMD_MAXIMIZE\0"
    "ERR_NO\0ERR_OK\0ERR_NETWORK\0ERR_APP_REGISTER\0"
    "ERR_APP_LOGIN\0ERR_APP_LOGOUT\0"
    "ERR_APP_RESET_PASSWD\0ERR_APP_MODIFY_PASSWD\0"
    "ERR_APP_SET_PAYCODE\0ERR_APP_RECHARGE\0"
    "ERR_APP_GET_RECHARGE_RECORD\0"
    "ERR_APP_PARKING_NEAR\0ERR_APP_PARKING\0"
    "ERR_APP_PARK_CONFIRM\0ERR_APP_PARK_PREPAY\0"
    "ERR_APP_PARK_FEE\0ERR_APP_PARK_RESTTIME\0"
    "ERR_APP_PARK_SETTLE\0ERR_APP_GET_PARK_UNPAY\0"
    "ERR_APP_PARK_PAY_IN_BACK\0"
    "ERR_APP_GET_PARK_RECORD\0"
    "ERR_APP_CHECK_FOR_UPDATE\0ERR_APP_GET_SYSINFO\0"
    "ERR_APP_FEEDBACK\0ERR_APP_CALL_ATTENDANT\0"
    "ERR_APP_GET_CREDIT\0ERR_APP_ADD_VEHICLE\0"
    "ERR_APP_DEL_VEHICLE\0ERR_APP_UPDATE_VEHICLE\0"
    "ERR_APP_ALIPAY\0ERR_APP_WXPAY\0"
    "ERR_HANDSET_REGISTER\0ERR_HANDSET_LOGIN\0"
    "ERR_HANDSET_LOGOUT\0ERR_HANDSET_ENQUIRY_SPACE\0"
    "ERR_HANDSET_PUSH_SPACEINFO\0"
    "ERR_HANDSET_BIND_CAR_SPACE\0"
    "ERR_HANDSET_PARK_CONFIRM\0ERR_HANDSET_PARK_FEE\0"
    "ERR_HANDSET_PARK_RESTTIME\0"
    "ERR_HANDSET_PARK_SETTLE\0"
    "ERR_HANDSET_GET_PARK_UNPAY\0"
    "ERR_HANDSET_PARK_PAY_IN_BACK\0"
    "ERR_HANDSET_PARK_QUERY\0ERR_SENSOR_UPDATE_SPACE\0"
    "ERR_HANDSET_RESP_CALLING\0ERR_MAXIMIZE"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_Common[] = {

 // content:
       7,       // revision
       0,       // classname
       0,    0, // classinfo
       0,    0, // methods
       0,    0, // properties
       5,   14, // enums/sets
       0,    0, // constructors
       0,       // flags
       0,       // signalCount

 // enums: name, flags, count, data
       1, 0x0,    6,   34,
       8, 0x0,    2,   46,
      11, 0x0,   16,   50,
      28, 0x0,   45,   82,
      74, 0x0,   46,  172,

 // enum data: key, value
       2, uint(Common::APP_MODULE_MAIM),
       3, uint(Common::APP_MODULE_SECURITY),
       4, uint(Common::APP_MODULE_MYWALLET),
       5, uint(Common::APP_MODULE_PARK_RECORD),
       6, uint(Common::APP_MODULE_VEHICLE),
       7, uint(Common::APP_MODULE_SETTING),
       9, uint(Common::PAY_MODE_PREPAY),
      10, uint(Common::PAY_MODE_POSTPAY),
      12, uint(Common::PAY_SOURCE_USER_PARK),
      13, uint(Common::PAY_SOURCE_USER_WXPAY),
      14, uint(Common::PAY_SOURCE_USER_ALIPAY),
      15, uint(Common::PAY_SOURCE_USER_BAIDUWALLET),
      16, uint(Common::PAY_SOURCE_USER_BANK),
      17, uint(Common::PAY_SOURCE_USER_COUPON),
      18, uint(Common::PAY_SOURCE_USER_CITYSMARTCARD),
      19, uint(Common::PAY_SOURCE_USER_CASH),
      20, uint(Common::PAY_SOURCE_OWNER_PARKING),
      21, uint(Common::PAY_SOURCE_OWNER_WXPAY),
      22, uint(Common::PAY_SOURCE_OWNER_ALIPAY),
      23, uint(Common::PAY_SOURCE_OWNER_BAIDUWALLET),
      24, uint(Common::PAY_SOURCE_OWNER_BANK),
      25, uint(Common::PAY_SOURCE_OWNER_COUPON),
      26, uint(Common::PAY_SOURCE_OWNER_CITYSMARTCARD),
      27, uint(Common::PAY_SOURCE_OWNER_CASH),
      29, uint(Common::CMD_APP_REGISTER),
      30, uint(Common::CMD_APP_LOGIN),
      31, uint(Common::CMD_APP_LOGOUT),
      32, uint(Common::CMD_APP_RESET_PASSWD),
      33, uint(Common::CMD_APP_MODIFY_PASSWD),
      34, uint(Common::CMD_APP_SET_PAYCODE),
      35, uint(Common::CMD_APP_RECHARGE),
      36, uint(Common::CMD_APP_GET_RECHARGE_RECORD),
      37, uint(Common::CMD_APP_PARKING_NEAR),
      38, uint(Common::CMD_APP_PARKING),
      39, uint(Common::CMD_APP_PARK_CONFIRM),
      40, uint(Common::CMD_APP_PARK_PREPAY),
      41, uint(Common::CMD_APP_PARK_FEE),
      42, uint(Common::CMD_APP_PARK_RESTTIME),
      43, uint(Common::CMD_APP_PARK_SETTLE),
      44, uint(Common::CMD_APP_GET_PARK_UNPAY),
      45, uint(Common::CMD_APP_PARK_PAY_IN_BACK),
      46, uint(Common::CMD_APP_GET_PARK_RECORD),
      47, uint(Common::CMD_APP_CHECK_FOR_UPDATE),
      48, uint(Common::CMD_APP_GET_SYSINFO),
      49, uint(Common::CMD_APP_FEEDBACK),
      50, uint(Common::CMD_APP_CALL_ATTENDANT),
      51, uint(Common::CMD_APP_GET_CREDIT),
      52, uint(Common::CMD_APP_ADD_VEHICLE),
      53, uint(Common::CMD_APP_DEL_VEHICLE),
      54, uint(Common::CMD_APP_UPDATE_VEHICLE),
      55, uint(Common::CMD_APP_LOCATE),
      56, uint(Common::CMD_APP_ALIPAY),
      57, uint(Common::CMD_APP_WXPAY),
      58, uint(Common::CMD_HANDSET_REGISTER),
      59, uint(Common::CMD_HANDSET_LOGIN),
      60, uint(Common::CMD_HANDSET_LOGOUT),
      61, uint(Common::CMD_HANDSET_ENQUIRY_SPACE),
      62, uint(Common::CMD_HANDSET_PUSH_SPACEINFO),
      63, uint(Common::CMD_HANDSET_BIND_CAR_BAY),
      64, uint(Common::CMD_HANDSET_PARK_CONFIRM),
      65, uint(Common::CMD_HANDSET_PARK_FEE),
      66, uint(Common::CMD_HANDSET_PARK_RESTTIME),
      67, uint(Common::CMD_HANDSET_PARK_SETTLE),
      68, uint(Common::CMD_HANDSET_GET_PARK_UNPAY),
      69, uint(Common::CMD_HANDSET_PARK_PAY_IN_BACK),
      70, uint(Common::CMD_HANDSET_PARK_QUERY),
      71, uint(Common::CMD_HANDSET_RESP_CALLING),
      72, uint(Common::CMD_SENSOR_UPDATE_SPACE),
      73, uint(Common::CMD_MAXIMIZE),
      75, uint(Common::ERR_OK),
      76, uint(Common::ERR_NETWORK),
      77, uint(Common::ERR_APP_REGISTER),
      78, uint(Common::ERR_APP_LOGIN),
      79, uint(Common::ERR_APP_LOGOUT),
      80, uint(Common::ERR_APP_RESET_PASSWD),
      81, uint(Common::ERR_APP_MODIFY_PASSWD),
      82, uint(Common::ERR_APP_SET_PAYCODE),
      83, uint(Common::ERR_APP_RECHARGE),
      84, uint(Common::ERR_APP_GET_RECHARGE_RECORD),
      85, uint(Common::ERR_APP_PARKING_NEAR),
      86, uint(Common::ERR_APP_PARKING),
      87, uint(Common::ERR_APP_PARK_CONFIRM),
      88, uint(Common::ERR_APP_PARK_PREPAY),
      89, uint(Common::ERR_APP_PARK_FEE),
      90, uint(Common::ERR_APP_PARK_RESTTIME),
      91, uint(Common::ERR_APP_PARK_SETTLE),
      92, uint(Common::ERR_APP_GET_PARK_UNPAY),
      93, uint(Common::ERR_APP_PARK_PAY_IN_BACK),
      94, uint(Common::ERR_APP_GET_PARK_RECORD),
      95, uint(Common::ERR_APP_CHECK_FOR_UPDATE),
      96, uint(Common::ERR_APP_GET_SYSINFO),
      97, uint(Common::ERR_APP_FEEDBACK),
      98, uint(Common::ERR_APP_CALL_ATTENDANT),
      99, uint(Common::ERR_APP_GET_CREDIT),
     100, uint(Common::ERR_APP_ADD_VEHICLE),
     101, uint(Common::ERR_APP_DEL_VEHICLE),
     102, uint(Common::ERR_APP_UPDATE_VEHICLE),
     103, uint(Common::ERR_APP_ALIPAY),
     104, uint(Common::ERR_APP_WXPAY),
     105, uint(Common::ERR_HANDSET_REGISTER),
     106, uint(Common::ERR_HANDSET_LOGIN),
     107, uint(Common::ERR_HANDSET_LOGOUT),
     108, uint(Common::ERR_HANDSET_ENQUIRY_SPACE),
     109, uint(Common::ERR_HANDSET_PUSH_SPACEINFO),
     110, uint(Common::ERR_HANDSET_BIND_CAR_SPACE),
     111, uint(Common::ERR_HANDSET_PARK_CONFIRM),
     112, uint(Common::ERR_HANDSET_PARK_FEE),
     113, uint(Common::ERR_HANDSET_PARK_RESTTIME),
     114, uint(Common::ERR_HANDSET_PARK_SETTLE),
     115, uint(Common::ERR_HANDSET_GET_PARK_UNPAY),
     116, uint(Common::ERR_HANDSET_PARK_PAY_IN_BACK),
     117, uint(Common::ERR_HANDSET_PARK_QUERY),
     118, uint(Common::ERR_SENSOR_UPDATE_SPACE),
     119, uint(Common::ERR_HANDSET_RESP_CALLING),
     120, uint(Common::ERR_MAXIMIZE),

       0        // eod
};

void Common::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
{
    Q_UNUSED(_o);
    Q_UNUSED(_id);
    Q_UNUSED(_c);
    Q_UNUSED(_a);
}

const QMetaObject Common::staticMetaObject = {
    { &QObject::staticMetaObject, qt_meta_stringdata_Common.data,
      qt_meta_data_Common,  qt_static_metacall, Q_NULLPTR, Q_NULLPTR}
};


const QMetaObject *Common::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
}

void *Common::qt_metacast(const char *_clname)
{
    if (!_clname) return Q_NULLPTR;
    if (!strcmp(_clname, qt_meta_stringdata_Common.stringdata0))
        return static_cast<void*>(const_cast< Common*>(this));
    return QObject::qt_metacast(_clname);
}

int Common::qt_metacall(QMetaObject::Call _c, int _id, void **_a)
{
    _id = QObject::qt_metacall(_c, _id, _a);
    if (_id < 0)
        return _id;
    return _id;
}
QT_END_MOC_NAMESPACE
